# Generated by Django 4.2 on 2023-05-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='udate',
            new_name='updated',
        ),
    ]
